name: PlayerVisibility
api-version: 1.16
version: 1.0
load: POSTWORLD
main: de.faidhd.playervisibility.PlayerVisibilityPlugin

commands:
  playervisibility:
    permission: playerhider.use
    aliases:
      - pv